### ISSUE TITLE
插件报错, 不能使用重构功能

### ISSUE THREAD

**Issue by lvgocc** [kana112233/mybatis-plus-plugin#26]
c插件经常弹出以下错误
![QQ截图20200403143702](https://user-images.githubusercontent.com/40954392/78331444-9d32b600-75b8-11ea-9d42-7bb9acd1fe64.png)
出错时, 不能使用重构功能
![QQ截图20200403143806](https://user-images.githubusercontent.com/40954392/78331504-c0f5fc00-75b8-11ea-898c-1ef10cd88a63.png)

**Comment by kana112233** [comment]
请提供你的idea的版本和插件的版本。顺便说一下，如果你的idea版本太旧，请更新你的idea。

**Comment by lvgocc** [comment]
[image: image.png]
[image: image.png]

kana112233 <notifications@github.com> 于2020年4月3日周五 下午2:47写道：

**Comment by kana112233** [comment]
请写清楚你的想法，写完之后确认一下你写的是否正确。
