### ISSUE TITLE
升级idea版本后 编辑mapper xml文件 idea无响应

### ISSUE THREAD

**Issue by zhangygit** [kana112233/mybatis-plus-plugin#27]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
升级idea版本，目前版本为2019.3.4（windows）
升级后，一编辑xml文件idea就无响应了。
但我也不能确定是否就是这个插件起的问题 ，我把所有mybatis的插件（除了这个）都卸载重装。就不能复现了。
我只是怀疑是这个插件的问题。不知道从哪看插件日志啥的
升级前没有问题的，插件很好用，升级后，就这样了，一编辑就无响应，关闭重开还这样。

2. What did you expect to see?
这个版本的idea解决下这个问题

3. What version of MybatisPlus are you using?
版本是 1.3.6

**Comment by kana112233** [comment]
1. 查看Idea插件日志的步骤： Idea菜单 -> Help -> Show Log in Explorer -> idea.log文件
你可以先删除这个 idea.log文件，再重新操作触发Bug，这样查找更容易。
2. 我不能重现这个问题。
3. 等你的idea.log文件。
