### ISSUE TITLE
idea mapper xml resultType 报错

### ISSUE THREAD

**Issue by litongjava** [kana112233/mybatis-plus-plugin#28]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
version
![image](https://user-images.githubusercontent.com/31761981/81887265-4d8cd480-95d1-11ea-86f4-83258b6a359e.png)
resultType是别名,但是报错

mapper interface还报错
![image](https://user-images.githubusercontent.com/31761981/81887405-9ba1d800-95d1-11ea-93f2-62a480559e2c.png)
 
我也写了一份到
https://segmentfault.com/q/1010000022638332

**Comment by kana112233** [comment]
你可以把你的Xml的resultType 改成resultMap，这样应该就不会报错了
![segmentfault 的图片](https://image-static.segmentfault.com/386/112/3861129727-5ebcaad3ea359_articlex)
