### ISSUE TITLE
可选的生成模块

### ISSUE THREAD

**Issue by thyxsl** [kana112233/mybatis-plus-plugin#30]
可以设置只生成 entity（或者其他模块） 模块的选项么， 默认好像全部生成的

**Comment by kana112233** [comment]
已经开始增加设置，请等待下一个版本。

**Comment by kana112233** [comment]
> 可以设置只生成 entity（或者其他模块） 模块的选项么， 默认好像全部生成的

版本1.4.1可以设置只生成 entity了,可以下载使用.
