### ISSUE TITLE
如何选DB的驱动

### ISSUE THREAD

**Issue by wowsonsun** [kana112233/mybatis-plus-plugin#35]
如题，因为某些原因不得不用低版本的DB驱动，这里用的mysql
![image](https://user-images.githubusercontent.com/23351005/92299837-9f92a500-ef88-11ea-9043-c2aba68e2870.png)

**Comment by kana112233** [comment]
出现“CLIENT_PLUGIN_AUTH”这个错误的原因应该是MySQL是5.1或低于的版本，而当前插件用的是mysql-connector-java: 8.0.16,可以使用[独立发布的mysql5.1版本插件](https://plugins.jetbrains.com/plugin/12670-mybatisplus/versions/mysql5.1/97111),手动下载安装。
源代码在[分支mysql5.1.x](https://github.com/kana112233/mybatis-plus-plugin/tree/mysql5.1.x)
