### ISSUE TITLE
下载新插件404

### ISSUE THREAD

**Issue by radcat1987** [kana112233/mybatis-plus-plugin#41]
下载新插件404
![image](https://user-images.githubusercontent.com/1320466/94543022-1ebf8400-027c-11eb-9516-a085c802414f.png)

**Comment by kana112233** [comment]
hi @radcat1987，非常感谢您的反馈，但是由于您没有使用[创建issue模板](https://github.com/kana112233/mybatis-plus-plugin/issues/new/choose) 提交， 将会直接被关闭， 谢谢！

**Comment by kana112233** [comment]
这个是idea网站的错误，我不能改变，你可从[这里下载](https://github.com/kana112233/mybatis-plus-plugin/releases/download/v1.4.2/MybatisPlus-1.4.2.zip)
