### ISSUE TITLE
可能会导致idea 2020.2.3窗口假死一段时间

### ISSUE THREAD

**Issue by wowsonsun** [kana112233/mybatis-plus-plugin#42]
## Bug Report(我要报Bug)

Please answer these questions before submitting your issue. Thanks!(提问前请先回答下面的问题,谢谢!)

1. What did you do?(你做了什么?)
If possible, provide a recipe for reproducing the error.(重现Bug的过程)

idea中点击方法上面的usage或者编写mybatis映射文件的时候窗口会假死十几秒以上，发生概率大概50%
![image](https://user-images.githubusercontent.com/23351005/98375605-4aa10700-207d-11eb-8f82-373426f0792c.png)

贴上idea日志
![image](https://user-images.githubusercontent.com/23351005/98375714-7623f180-207d-11eb-9b64-af69fd968e5a.png)
[threadDump-20201105-164928.txt](https://github.com/kana112233/mybatis-plus-plugin/files/5501661/threadDump-20201105-164928.txt)
[threadDump-20201105-164933.txt](https://github.com/kana112233/mybatis-plus-plugin/files/5501664/threadDump-20201105-164933.txt)

2. What did you expect to see?(期待的结果是什么样的?)

3. What did you see instead?(实际的结果是什么样的?)

4. What version of MybatisPlus are you using?(使用MybatisPlus的版本?)

1.5.1

**Comment by kana112233** [comment]
可以在这里下载修复的版本 MybatisPlus-1.5.2.zip
https://github.com/kana112233/mybatis-plus-plugin/releases/tag/v1.5.2
或者 MybatisPlus-1.4.4.zip
https://github.com/kana112233/mybatis-plus-plugin/releases/tag/v1.4.4
