### ISSUE TITLE
苹果电脑中编辑mapper会自动删除英文格式的点"."

### ISSUE THREAD

**Issue by 16beer** [kana112233/mybatis-plus-plugin#43]
IntelliJ IDEA 2020.2.3 (Community Edition)
Build #IC-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: documentation.show.toolbar=true
Non-Bundled Plugins: DBN, Lombook Plugin, com.alibaba.p3c.smartfox, cn.yiiguxing.plugin.translate, com.baomidou.plugin.idea.mybatisPlus

上面是Idea的信息，插件版本：1.2.3

在mapper中打入英文点【.】会被自动删除，随后光标向左移动回去，禁用插件后问题就没有了。

**Comment by kana112233** [comment]
hi @16beer，非常感谢您的反馈，但是由于您没有使用[创建issue模板](https://github.com/kana112233/mybatis-plus-plugin/issues/new/choose) 提交， 将会直接被关闭， 谢谢！
