### ISSUE TITLE
在IDea2020.3的版本，安装该插件后，     在xxxxMppaer.xml中写sql时，会导致idea卡死

### ISSUE THREAD

**Issue by yangttie** [kana112233/mybatis-plus-plugin#48]
## Bug Report(我要报Bug)

Please answer these questions before submitting your issue. Thanks!(提问前请先回答下面的问题,谢谢!)

1. What did you do?(你做了什么?)
If possible, provide a recipe for reproducing the error.(重现Bug的过程)
在mapper.xml中修改sql语句，会导致idea卡死

2. What did you expect to see?(期待的结果是什么样的?)

3. What did you see instead?(实际的结果是什么样的?)

4. What version of MybatisPlus are you using?(使用MybatisPlus的版本?)

3.4.1

**Comment by kana112233** [comment]
不能重现 MybatisPlus没有版本3.4.1

**Comment by likechestnuts** [comment]
是卡死的
