### ISSUE TITLE
关于数据库驱动的问题

### ISSUE THREAD

**Issue by CobraStarLE** [kana112233/mybatis-plus-plugin#58]
作者，你好，你能添加自定义数据库驱动的界面吗，你现在代码的驱动有些老旧，mysql有些版本的数据库连不上，希望你能支持一下，谢谢！

**Comment by kana112233** [comment]
hi @CobraStarLE，非常感谢您的反馈，但是由于您没有使用[创建issue模板](https://github.com/kana112233/mybatis-plus-plugin/issues/new/choose) 提交， 将会直接被关闭， 谢谢！
