### ISSUE TITLE
IdType问题

### ISSUE THREAD

**Issue by jaychuo** [kana112233/mybatis-plus-plugin#62]
## IdType问题

新版的mybatisplus的IdType的问题:

- 新版的mybatisplus的IdType更新：
    AUTO(0),
    NONE(1),
    INPUT(2),
    ASSIGN_ID(3),
    ASSIGN_UUID(4);

**Comment by kana112233** [comment]
hi @jaychuo，非常感谢您的反馈，但是由于您没有使用[创建issue模板](https://github.com/kana112233/mybatis-plus-plugin/issues/new/choose) 提交， 将会直接被关闭， 谢谢！
