### ISSUE TITLE
XML

### ISSUE THREAD

**Issue by galfordliu** [kana112233/mybatis-plus-plugin#67]
版本：1.7.1
BUG描述：
在XML中插入使用CDATA部分环绕功能时，生成的格式不正确：
例如
<code>
<![CDATA[   login_time < #{endTime}  ]]<
</code>
最后一个符号错了。理应是
<code>
<![CDATA[   login_time < #{endTime}  ]]>
</code>

**Comment by kana112233** [comment]
hi @galfordliu，非常感谢您的反馈，但是由于您没有使用[创建issue模板](https://github.com/kana112233/mybatis-plus-plugin/issues/new/choose) 提交， 将会直接被关闭， 谢谢！
