### ISSUE TITLE
换色请求

### ISSUE THREAD

**Issue by suckTypeWorker** [kana112233/mybatis-plus-plugin#70]
能否给xml图标换个别的颜色。我用的主题是Visual Studio Code Dark Plus，xml的图标不是很明显

**Comment by kana112233** [comment]
hi @suckTypeWorker，非常感谢您的反馈，但是由于您没有使用[创建issue模板](https://github.com/kana112233/mybatis-plus-plugin/issues/new/choose) 提交， 将会直接被关闭， 谢谢！

**Comment by kana112233** [comment]
> 能否给xml图标换个别的颜色。我用的主题是Visual Studio Code Dark Plus，xml的图标不是很明显

可以考虑
