### ISSUE TITLE
generate - Entity  

### ISSUE THREAD

**Issue by xuzhou2016** [kana112233/mybatis-plus-plugin#73]
## Bug Report(我要报Bug)

Please answer these questions before submitting your issue. Thanks!(提问前请先回答下面的问题,谢谢!)

1. What did you do?(你做了什么?)
If possible, provide a recipe for reproducing the error.(重现Bug的过程)

你好： 用这个idea插件，  感觉非常好
            但是有一个地方，请帮忙修改一下
            生成的 Entity 对象。 没有 TableName( )   注解

             --- TableName( ） 也许不是必须的， 但是应该加上。
             比如： 数据库里面有 100张表， 自动生成后
              一个一个手动添加，比较麻烦， 请理解
             可以不考虑 table_prefix 之类的。 
            数据库表名即可， 
            比如： t_sys_user_info_log    -->   **@TableName**("t_sys_user_info_log")

非常感谢！！

2. What did you expect to see?(期待的结果是什么样的?)
   带有 TableName  Annotation

3. What did you see instead?(实际的结果是什么样的?)
没有 注解

4. What version of MybatisPlus are you using?(使用MybatisPlus的版本?)
3.4.0

**Comment by kana112233** [comment]
按照[这个地方操作](https://github.com/kana112233/mybatis-plus-plugin/wiki/code-generate#%E8%87%AA%E5%AE%9A%E4%B9%89controller%E7%94%9F%E6%88%90curd)应该可以解决你的问题
你可以修改[这个文件](https://github.com/kana112233/mybatis-plus-plugin/blob/dev/templates/entity.java.ftl)，在里面加入注解TableName
