### ISSUE TITLE
首先感谢分享，在使用中有几个问题，不知有没有解决方法

### ISSUE THREAD

**Issue by lWoHvYe** [kana112233/mybatis-plus-plugin#8]
1、在xml中编写sql的时候，输入空格会出现提示，再输入空格会插入提示的内容，不知能否改成输入回车才插入提示的内容
2、在出现提示内容的时候，输入等号，也会插入提示的内容，这在编写条件时很不方便，不知能否优化一下
这两个问题导致在使用时有些不方便，不知能否予以解决，感谢

**Comment by kana112233** [comment]
已解决，请下载最新版

**Comment by Justonly5** [comment]
> 已解决，请下载最新版

请问最新版的是哪个版本?我已经更新过了 还是有这些问题..

**Comment by kana112233** [comment]
这是版本列表 https://plugins.jetbrains.com/plugin/12670-mybatisplus/versions 
最新版本1.3.4
如果你的idea版本小于2019.2，你应该更新idea啦
